Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\prefetch\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\softwaredistribution\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\temp\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:systemdrive\Windows.Old"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:temp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:userprofile\AppData\Local\Microsoft\Windows\INetCache\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:systemdrive\temp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CarbonBlack"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CbsTemp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\ccmcache"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CCM\Temp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CCM\Inventory\Temp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CCM\Logs\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CCM\SystemTemp"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:windir\CCM\Staging\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:programdata\Microsoft\Windows\WER\Temp\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:programdata\Microsoft\Windows\WER\ReportArchive\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:programdata\Microsoft\Windows\WER\ReportQueue\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Windows\Explorer\*.db"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\DtcInstall.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\comsetup.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\PFRO.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\setupact.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\setuperr.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\setupapi.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Panther\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\inf\setupapi.app.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\inf\setupapi.dev.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\inf\setupapi.offline.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Performance\WinSAT\winsat.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\debug\PASSWD.LOG"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Windows\WebCache\*.*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\ServiceProfiles\LocalService\AppData\Local\Temp\*.*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\CBS\CBS.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\DISM\DISM.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\SIH\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\CLR_v4.0\UsageTraces\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\CLR_v4.0_32\UsageTraces\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\NetSetup\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\LogFiles\setupcln\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Temp\CBS\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\waasmedic"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\catroot2\dberr.txt"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\catroot2.log"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\catroot2.jrs"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\catroot2.edb"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\System32\catroot2.chk"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Logs\SIH\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:SystemRoot\Traces\WindowsUpdate\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Windows\INetCache\IE\*"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Internet Explorer"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:appdata\Microsoft\Windows\Cookies"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:userprofile\Cookies"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:userprofile\Local Settings\Traces"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Temporary Internet Files"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Windows\Temporary Internet Files"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Windows\INetCookies\PrivacIE"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\Feeds Cache"
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:LocalAppData\Microsoft\InternetExplorer\DOMStore"

Clear-RecycleBin -Force -ErrorAction SilentlyContinue
Clear-BCCache -Force -ErrorAction SilentlyContinue
Clear-DnsClientCache

#takeown /F "$env:programdata\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl" /R
#icacls "$env:programdata\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl" /grant administrators:F /t
#Write-Output "" > "$env:programdata\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl"
#Write-Output Clear successful: "$env:programdata\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl"

#takeown /f $env:SystemRoot\Logs\waasmedic /r -Value y
#icacls $env:SystemRoot\Logs\waasmedic /grant administrators:F /t

#reg delete "HKCU\SOFTWARE\Microsoft\Internet Explorer\TypedURLs" /va /f
#reg delete "HKCU\SOFTWARE\Microsoft\Internet Explorer\TypedURLsTime" /va /f
